### ISSUE TITLE
Setting NVCC flags on CMake

### ISSUE THREAD

**Issue by joaovbs96** [ingowald/RTOW-OptiX#1]
Is there any way to set NVCC flags in the CMake script that's used by the project? I'm trying to add a callable program to the code, but[ apparently the flag `--relocatable-device-code=true` is needed.](https://devtalk.nvidia.com/default/topic/1000376/?comment=5111537) Would be great to be able to set the architecure and compute as well. Tried some things after reading the CMake documentation but had no luck.

**Comment by ingowald** [comment]
Yes, there is. I had to read through some code myself to answer that, because what you're asking for is not actually a cmake question per se, but rather a question on how James Bigler's CUDA cmake module works ...

To explain: My cmakefile builds some rules to comile and embed the .cu files; but the actual nvcc compilation step is done by the "cuda_compile_ptx()" function from the cmake cuda module (typically found in /usr/share/cmake-3.10/Modules/FindCUDA.cmake). Reading through that I eventually found a "OPTIONS" mechanism to pass options through to CUDA, and after just testing it just out I can confirm that this does indeed work.

To use that for your particular purpose: 
- go to RTOW-Optix/cmake/configure_optix.cmake
- find the "cuda_compile_and_embed" macro at the bottom
- find where this macro calls "cuda_compile_ptx"
- change that call from
 cuda_compile_ptx(ptx_files ${cuda_file})
to
 cuda_compile_ptx(ptx_files ${cuda_file} OPTIONS -my-cuda-arg)

**Comment by joaovbs96** [comment]
Thanks a lot! That solved my issue.

I was attempting to use these (bindless) callable programs I mentioned to emulate how Mr. Shirley's texture objects/functions work in his CPU code of the second book, as a way to 'sample' the texture assigned to a material, given u/v/p parameters. Apparently, it's working like a charm.
