### ISSUE TITLE
error: identifier "uint64_t" is undefined when compiling on Windows 10

### ISSUE THREAD

**Issue by ghost** [ingowald/RTOW-OptiX#6]
Dear sir, 

I'm trying to compile and run this repository on my Windows 10 machine. I've installed both CUDA 10 and Optix 5.1.1, added CUDA to the PATH correctly (I can use `nvcc`) and also set an `OptiX_INSTALL_DIR` environment variable with the correct install location (it's the same the `cmake/FindOptiX.cmake` looks for). I am using VS Code with the CMake plugin. 

The project gets configured properly, but when I hit build, both the iterative and recursive versions have this issue where they can't find the `uint64_t` symbol and fail to compile. 

Any idea what could be causing this?

Thanks a lot in advance.

**Comment by ingowald** [comment]
Hm. I'm not sure I ever tested this project under windows - I primarily develop under linux, and though I do keep some of the larger projects cross-platform, for this one I'm not sure I ever did.

If you do want to port his code over to windows, this particular error is easy to fix by adding a "typedef unsigned long long uint64_t"; however, there's a good chance that there'll be other windows-specific issues, so not sure if that route makes sense.

Alternatively, I'd point you towards a much newer version of this sample in a much newer library (that also uses the latest OptiX 7, not older 5.5), and that we also keep cross-platform, so should build on Windows, too. If that is of interest, have a look at the complete project here: https://owl-project.github.io/ ; the particular shirley RTOW example is sample 5: https://github.com/owl-project/owl/tree/master/samples/s05-rtow .

**Comment by ghost** [comment]
Thank you very much for the swift and very kind answer!

I actually did the typedef, and everything works! 

However, since I'm curious about the new project by you and Mr Shirley, I was wondering whether that one is meant to be different, like, less "easy to read" and/or less based on RTOW. I'm really a beginner on GPU stuff and I'm trying to use these as learning resources, so thank you very much for providing these examples!

**Comment by ingowald** [comment]
Glad that this works now! If you want, you can put a #ifdef _WIN32 around that typedef, and send me a PR - not sure how many people still use this optix 5 example, but maybe somebody else will stumble over it, too.

Re OWL: The motivation there was to bring some of the OptiX 5/Optix 6 API back to OptiX 7: If you look at the OptiX 5 RTOW code you have you'll see that there is pretty minimal host-side code to set up the scene, and all the "real" code is (as it should be) in the CUDA file that runs on the device. In OptiX 7, however, the OptiX API changed to become much more low-level, and the same host-side setup code would now be _much_ longer, and requires understanding of concepts like Shader Binding Tables, etc. 

That is actually a good thing for many applications that do want the low-level control and performance, but in particular for smallish projects and novel users can be a bit intimidating.

The goal of OWL is to build on top of OptIX 7, and add this "convenience" functionality to make it look more like OptiX 5 or 6. It's not a perfect match in any way (ie, you can' tjust "recompile" an existing 5 or 6 program with OWL, but for somebody that's used to the 5/6 abstration level, getting "something" up and running with OWL should be rather easy.

Closing this since you code now seems to work!
